### **TASK 1**
Use the implementation of perceptron from the last lab manual and model the truth table of XOR.

![XOR](./XOR.png "XOR")


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
data = [[0,0,0], [0,1,1],[1,0,1], [1,1,0]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['A', 'B','AXORB'])
 
df


A  B  AXORB
0  0  0      0
1  0  1      1
2  1  0      1
3  1  1      0

In [4]:
X_train=df[['A','B']]
Y_train=df['AXORB']
#to avoid class invalance we use train_test_split() fun as in data set first it has R data then M 

In [5]:
X_train = np.array(X_train)
# X_test = np.array(X_test)
Y_train = np.array(Y_train)
# y_test = np.array(y_test)

In [6]:
X_train=X_train.T

In [17]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [8]:
numOfTrainSamples = X_train.shape[1]

In [9]:
np.expand_dims(Y_train,axis =0)

array([[0, 1, 1, 0]])

In [10]:
y_train = np.expand_dims(Y_train,axis =0)
y_train.shape

(1, 4)

In [11]:
#---- As weights are known so no need -----#

# W = np.random.rand(2,1)
# print(W.shape)
# print('W:',W)

# print(numOfTrainSamples)
# X_train

In [12]:
 #-----As weights are known so no need ----#
#  b = np.random.rand()
#  b


# Here are finded Weights

In [13]:
 w=np.array([[0.39857326],
 [0.79448032]])

In [14]:
train_weights=np.array([-0.32612598])

In [15]:
b=train_weights

In [16]:
from sklearn.metrics import log_loss

alpha = 0.01

for n in range(100):

    # Net input function output
    Z = np.dot(w.T,X_train,) + b
#     Z = np.dot(train_weights.T,X_train,) + train_bias
    
    # Activation function 
    A = sigmoid(Z)

    
    # To change values to int
    A = np.where(A < 0.5, 0, 1)

    
#     print(A)
    
    # Loss Function 
    # ----- As weights are find sp no need to update weights----------#
#     J = log_loss(y_train,A)
#     print("Error:",J)

#     dz = A - y_train
#     dw = np.dot(X_train,dz.T)/numOfTrainSamples
#     db = np.sum(dz,axis =1)/numOfTrainSamples
    
    
#     W = W - alpha * dw
#     b = b - alpha *db


In [17]:
A

array([[0, 1, 1, 1]])

In [18]:
Y_train

array([0, 1, 1, 0])

### **TASK 2**
1. Import the diabetes dataset. You can find data description in the description file.
2. Use pandas plots to have a look and feel of the different attributes of the data.
3. Apply perceptron algorithm to model the data distribution.
4. Use mean squared error as your cost/ error function.
5. Use the below given derivatives to find gradients of each W.

![MSE](./MSE.png "MSE")

![MSE derivative](./derivativeMSE.png "MSE derivative")


In [20]:
columns = [i for i in range(1,12)]

# columns.append("label")
df2 = pd.read_csv("diabetes.txt",names=columns,delimiter = "\t",header=None)
df2.head()
# df.iloc[57]

1   2     3      4    5      6     7    8       9   10   11
0  59   2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1  48   1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2  72   2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3  24   1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4  50   1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [21]:

X2_train, X2_test, y2_train, y2_test = train_test_split(df2[columns[:-1]], df2[columns[-1]], test_size=0.33, random_state=42)
#to avoid class invalance we use train_test_split() fun as in data set first it has R data then M 

In [22]:
y2_train

231    154
325    192
193    116
109     81
195    122
      ... 
106    134
270    202
348    148
435     64
102    302
Name: 11, Length: 296, dtype: int64

In [23]:
df2.describe()

1           2           3           4           5           6   \
count  442.000000  442.000000  442.000000  442.000000  442.000000  442.000000   
mean    48.518100    1.468326   26.375792   94.647014  189.140271  115.439140   
std     13.109028    0.499561    4.418122   13.831283   34.608052   30.413081   
min     19.000000    1.000000   18.000000   62.000000   97.000000   41.600000   
25%     38.250000    1.000000   23.200000   84.000000  164.250000   96.050000   
50%     50.000000    1.000000   25.700000   93.000000  186.000000  113.000000   
75%     59.000000    2.000000   29.275000  105.000000  209.750000  134.500000   
max     79.000000    2.000000   42.200000  133.000000  301.000000  242.400000   

               7           8           9           10          11  
count  442.000000  442.000000  442.000000  442.000000  442.000000  
mean    49.788462    4.070249    4.641411   91.260181  152.133484  
std     12.934202    1.290450    0.522391   11.496335   77.093005  
min     22.000000    2.000000    3.258100   58.000000   25.000000  
25%     40.250000    3.000000    4.276700   83.250000   87.000000  
50%     48.000000    4.000000    4.620050   91.000000  140.500000  
75%     57.750000    5.000000    4.997200   98.000000  211.500000  
max     99.000000    9.090000    6.107000  124.000000  346.000000

In [24]:
X2_train

1   2     3       4    5      6     7     8       9    10
231  51   1  23.5  101.00  195  121.0  51.0  4.00  4.7449   94
325  48   1  31.4   75.33  242  151.6  38.0  6.37  5.5683  103
193  51   2  25.9   76.00  240  169.0  39.0  6.00  5.0752   96
109  59   2  25.5   95.33  190  139.4  35.0  5.43  4.3567  117
195  56   2  28.7   99.00  208  146.4  39.0  5.00  4.7274   97
..   ..  ..   ...     ...  ...    ...   ...   ...     ...  ...
106  22   1  19.3   82.00  156   93.2  52.0  3.00  3.9890   71
270  50   2  29.2  119.00  162   85.2  54.0  3.00  4.7362   95
348  57   1  24.5   93.00  186   96.6  71.0  3.00  4.5218   91
435  45   1  24.2   83.00  177  118.4  45.0  4.00  4.2195   82
102  23   1  29.0   90.00  216  131.4  65.0  3.00  4.5850   91

[296 rows x 10 columns]

In [25]:
X2_train = np.array(X2_train)
# X_test = np.array(X_test)
Y2_train = np.array(y2_train)
# y_test = np.array(y_test)

In [26]:
X2_train=X2_train.T

In [27]:
numOfTrainSamples = X2_train.shape[1]

In [28]:
np.expand_dims(Y2_train,axis =0)

array([[154, 192, 116,  81, 122, 259, 191, 292,  55, 107, 210,  91, 253,
         85, 252,  59,  78, 200,  78, 245, 175,  42, 127,  53,  94, 104,
        199, 265, 281, 248, 257, 215, 303, 170,  59, 277, 209, 138, 198,
        124,  96, 288, 225, 265, 101,  55, 198,  51, 252,  64, 220, 131,
        212, 142, 103, 155, 121,  86, 111,  65, 131,  51, 128, 141,  48,
        109, 178,  88,  84, 216, 150,  60,  96, 190,  74, 279, 182, 160,
        245, 276, 174, 180, 150, 196, 138,  97, 246, 321, 308, 109,  69,
        182, 258, 161, 178, 214,  45, 150, 160,  55, 197, 185, 268, 310,
        123,  68,  72, 185, 144, 147, 168, 178, 246, 151, 127,  83, 332,
        152, 109,  90,  66, 214,  85, 129,  89, 259, 229, 200,  77,  54,
         31, 109, 206, 144, 118,  83, 242, 259,  72, 163, 181, 141,  71,
        137, 195, 179, 102, 131,  47, 235,  77, 198,  93, 162, 225, 275,
        183, 306,  81,  55, 146, 196, 230, 310,  40, 135, 346,  43, 128,
         77, 235,  49,  74,  92,  84, 263, 144, 142

In [29]:
y2_train = np.expand_dims(Y2_train,axis =0)
print(y2_train.shape)
print(X2_train.shape)

(1, 296)
(10, 296)


In [62]:
W = np.random.rand(10,1)
print(W.T.shape)
print('W:',W.T)

print(numOfTrainSamples)



(1, 10)
W: [[0.30379979 0.03185807 0.02576841 0.07300683 0.41510308 0.63317897
  0.00359063 0.6610659  0.47298272 0.24830459]]
296


In [63]:
b = np.random.rand()
b

0.3059081913307359

In [64]:
print('W',W.shape)
print('X2',X2_train.shape)

W (10, 1)
X2 (10, 296)


In [65]:
from sklearn.metrics import mean_squared_error

In [81]:
from sklearn.metrics import log_loss

alpha = 0.001

for n in range(1):

    # Net input function output
    Z = np.dot(W.T,X2_train) + b

    print(Z)
    
    # Loss Function
    e= mean_squared_error(Z,y2_train)
    print('Error: ',e)
    dz=Z-y2_train


    dw = np.dot(X2_train,dz.T)/numOfTrainSamples
    db = np.sum(dz,axis =1)/numOfTrainSamples

    W = W - alpha * dw
    b = b - alpha *db


[[-2.77108144e+23 -3.15557863e+23 -3.19758996e+23 -2.86045399e+23
  -2.96848181e+23 -2.42920656e+23 -3.08996552e+23 -3.14063879e+23
  -2.59384416e+23 -2.62327784e+23 -2.11505398e+23 -2.82900153e+23
  -3.42704111e+23 -3.00071315e+23 -2.29686069e+23 -2.29827225e+23
  -2.28429062e+23 -2.49259169e+23 -3.15492322e+23 -2.61855806e+23
  -2.59044078e+23 -2.10469350e+23 -2.44388859e+23 -2.67328921e+23
  -2.56764363e+23 -2.20171267e+23 -2.15896185e+23 -2.69179074e+23
  -2.41012843e+23 -3.07150264e+23 -2.81929444e+23 -3.04751557e+23
  -2.61621794e+23 -3.20662168e+23 -2.79667919e+23 -2.63243763e+23
  -2.97252227e+23 -2.32297865e+23 -2.27529651e+23 -2.53776845e+23
  -2.59828685e+23 -2.47327299e+23 -2.83777580e+23 -2.46784838e+23
  -1.80841385e+23 -2.49836961e+23 -3.07999341e+23 -2.76792049e+23
  -3.44257268e+23 -2.20252897e+23 -2.93461394e+23 -3.58454667e+23
  -3.03271125e+23 -2.19139444e+23 -3.00637656e+23 -3.04444931e+23
  -3.63033372e+23 -2.27958643e+23 -2.62745413e+23 -2.98781457e+23
  -2.78080

In [80]:
y2_train.shape,Z.shape

((1, 296), (1, 296))

In [43]:
print(X2_train.shape),print(y2_train.T.shape)

(10, 296)
(296, 1)


(None, None)

In [52]:
y2_train[0]

array([154, 192, 116,  81, 122, 259, 191, 292,  55, 107, 210,  91, 253,
        85, 252,  59,  78, 200,  78, 245, 175,  42, 127,  53,  94, 104,
       199, 265, 281, 248, 257, 215, 303, 170,  59, 277, 209, 138, 198,
       124,  96, 288, 225, 265, 101,  55, 198,  51, 252,  64, 220, 131,
       212, 142, 103, 155, 121,  86, 111,  65, 131,  51, 128, 141,  48,
       109, 178,  88,  84, 216, 150,  60,  96, 190,  74, 279, 182, 160,
       245, 276, 174, 180, 150, 196, 138,  97, 246, 321, 308, 109,  69,
       182, 258, 161, 178, 214,  45, 150, 160,  55, 197, 185, 268, 310,
       123,  68,  72, 185, 144, 147, 168, 178, 246, 151, 127,  83, 332,
       152, 109,  90,  66, 214,  85, 129,  89, 259, 229, 200,  77,  54,
        31, 109, 206, 144, 118,  83, 242, 259,  72, 163, 181, 141,  71,
       137, 195, 179, 102, 131,  47, 235,  77, 198,  93, 162, 225, 275,
       183, 306,  81,  55, 146, 196, 230, 310,  40, 135, 346,  43, 128,
        77, 235,  49,  74,  92,  84, 263, 144, 142, 341, 115, 15

In [56]:
Z[0]

array([428.79319842, 445.76738516, 439.37164139, 431.7723378 ,
       435.73675017, 401.89856187, 458.14651317, 458.94627368,
       388.7578292 , 403.47653881, 348.29443759, 427.829476  ,
       469.83888151, 475.22777888, 388.11494925, 379.91895097,
       370.36314984, 414.70491148, 450.87181411, 391.14726809,
       440.89491827, 354.96722977, 393.63233657, 418.96637449,
       413.8670841 , 338.42397882, 355.77540817, 437.64154053,
       401.94591974, 471.4341027 , 443.88111453, 457.58375365,
       432.47092667, 475.74327339, 429.12310597, 421.79724488,
       429.80083794, 370.8407136 , 381.76382654, 366.81374899,
       380.97075528, 393.85044709, 420.44081674, 393.81581692,
       327.08889122, 384.35038741, 436.71766785, 409.75520074,
       500.72464683, 393.54934448, 462.3043183 , 486.63666943,
       444.15873957, 352.28226337, 512.55609768, 471.35024686,
       486.70726864, 384.90257715, 423.44123814, 461.51544131,
       446.91017289, 390.75578707, 419.89792651, 379.71